---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    mydbpass: AgBRBUsc2rrTWiQdlupBOHneUfriA7kQuXh1ySVjTkj0BHHeVtrtK8ETLiqf+RWhkPPwu4uxxqwyUmA5+kf4qStnBUymmrgHUMCVBYyzF/4u4w2qEUwCEM7hnDDmH9mipz4rN89sNQYdceDtO1/NkyTKgyFHPh/iX8fmHZuoDWV7nmPXLSXtyNI6UWJxeCucVOrRZ6NFl6y2yMeLWboXfyxorHMYVVIeLRlPGSmZ6fQbSTFthTvWAMiEeus967fiwgspkDGZuCo0B1DBsB8ID2UfsYTo2gXpr12+BTVtYeT3u6SGngbiZ0UKvtT4eVQwaDJw0TrsruRdZfFKxjfAScgomfhXwwfkg6Rt0cDqup3vVTzxE+rUA1hE7LaZ+DSjl7YHhjU3Lv+s5bsXe30d4aQFOMpC5tsNzjKMgo4Nz+gzByd+/kxD8gfQ9dEV1LIvZT8LN2M2QX0kkO4yUmJUZ8MMsze05DygfGnW3NqXm+eO3/cndM1kqDGNb0hfufYe4wr9D3G+ofp1bgUc1Onf1R21/qUhEOUR+Jap/GrHIEcirBxQSalH4d+PUF6sjqcrwqrmtUeLdefQNA72uxOmKRUlCj78W2WWCS6fyGUKxp3AW3SRMsCGM/YD/f+hQYCuWkin2W0z9nm2vQPtqNUPb4KE5KFUQTdHsj9emgFyCEoEgWCXTESvQDEhonAOkrHmsCKxryuzXnLGIe8O5vQNRw==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
